-   repo: git@github.com:pre-commit/pre-commit-hooks
    sha: f99d70ef0fed82851e32a8a8b34ab9e6e3eb2af5
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: autopep8-wrapper
        args:
        - -i
        - --ignore=E265,E309,E501
    -   id: check-json
    -   id: check-yaml
    -   id: debug-statements
    -   id: name-tests-test
    -   id: flake8
        args:
        - --exclude=**/migrations/*.py
-   repo: git@github.com:FalconSocial/pre-commit-python-sorter.git
    sha: 3d2f6802292d6413ad8312cd7c8be9c41409d326
    hooks:
    -   id: python-import-sorter
        args:
        - --silent-overwrite
